### ISSUE TITLE
No natural mob spawning? 

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#1062]
### Minecraft's Version

1.18.1 Purpur

### Plugin's Version

SuperiorSkyblock2-1.9.0-b595

### Describe the bug

-

### To Reproduce

-

### Additional Information

-

**Comment by OmerBenGera** [comment]
Natural mob spawning works as intended.
If it doesnt, it might be due to your spigot jar settings, another plugin blocking it or you might have disabled it in `/is settings`
Another reason might be that you are too close to spawning areas and therefore no mobs spawn there.


Next time you open an issue, dont leave blank fields

**Comment by Pikaronga** [comment]
> Natural mob spawning works as intended. If it doesnt, it might be due to your spigot jar settings, another plugin blocking it or you might have disabled it in `/is settings` Another reason might be that you are too close to spawning areas and therefore no mobs spawn there.
> 
> Next time you open an issue, dont leave blank fields

filled in the fields now that i've tested it a bit more

**Comment by OmerBenGera** [comment]
> > Natural mob spawning works as intended. If it doesnt, it might be due to your spigot jar settings, another plugin blocking it or you might have disabled it in `/is settings` Another reason might be that you are too close to spawning areas and therefore no mobs spawn there.
> > Next time you open an issue, dont leave blank fields
> 
> filled in the fields now that i've tested it a bit more
> 
> it atleast seems to slow the spawning a ton.

The plugin does not affect mob spawning
