### ISSUE TITLE
drop item disappear

### ISSUE THREAD

**Issue by ming11221122** [BG-Software-LLC/SuperiorSkyblock2#1252]
### Minecraft's Version

paper 1.18.2

### Plugin's Version

SuperiorSkyblock2-1.11.0-b710 

### Describe the bug

when player drop some item to border, the item will disappear

### To Reproduce

https://user-images.githubusercontent.com/104884332/178300530-3794793b-f162-45c5-a08b-6eeb4662d32d.mp4

**Comment by OmerBenGera** [comment]
What happens is that the client thinks the item should not go through the border, and therefore renders it like it bounds off the border. However, this border is not real, and the server doesn't know about this border, and therefore the server calculates the item as it thrown to the void. Then, it updates the client about the items movement and the client updates it, and that's why you see this visual bug.

Cannot be fixed on the plugin's side - try reporting it to Spigot/Paper, maybe they can fix it somehow.
