### ISSUE TITLE
Island Missions can't be completed by members

### ISSUE THREAD

**Issue by HzDeimos** [BG-Software-LLC/SuperiorSkyblock2#1270]
### Minecraft's Version

Paper
1.18.2

### Plugin's Version

1.11.0.720

### Describe the bug

I have an island mission related to the island level. The mission works well, however, it can only be completed by the island leader. How can i make it so that members can also complete this mission even if the island leader is offline?

### To Reproduce

Island Missions can't be completed by members.

### Additional Information

Here's the config for the mission. I excluded the icons section as i think I'ts not relavant to my issue.

https://pastebin.pl/view/07da14d5

**Comment by OmerBenGera** [comment]
IslandWorthUpdateEvent is a generic event that is not bound to a specific player. Therefore, the island's owner is used as the player that tried to complete it. The issue is with the way you configure your mission - you give the permission to only 1 player in the island while others also have that mission completed.

You'll have to rethink about how you do this mission, or code yohr own mission jar to do that for you.
