### ISSUE TITLE
afk-integrations (redstone)

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1414]
### Minecraft's Version

git-Purpur-1824 (MC: 1.19.2)

### Plugin's Version

[SuperiorSkyblock2-2022.8.1-b871.jar](https://hub.bg-software.com/job/SuperiorSkyblock2/lastSuccessfulBuild/artifact/target/SuperiorSkyblock2-2022.8.1-b871.jar)

### Describe the bug

I use CMI's AFK system, in the superiorskyblock configuration, I enabled the plugin to deactivate redstone when island members are AFK, it works great, however when a player is no longer AFK often the redstone does not reactivate, you have to reactivate everything by hand.

### To Reproduce

Put redstone disable when players in afk to true
AFK 5 minutes
Come back and redstone dont reactivated

**Comment by OmerBenGera** [comment]
This is probably because the redstone waits for a block-update after it was disabled.
Nothing that I can do regarding this - the solution would be to go through all the redstone components code-wise and trigger a block update, which is a really laggy and inefficient solution.
I'd say relogging is the easiest and fastest way to trigger the block-update :)
