### ISSUE TITLE
Nether Portal breaking causes massive lag

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#1442]
### Minecraft's Version

git-Purpur-1758 (MC: 1.19.2)

### Plugin's Version

SuperiorSkyblock2-2022.9-b896.jar

### Describe the bug

When breaking multiple nether portals a massive lag spike occurs and causes the server to run out of memory. This was linked back to SuperiorSkyblock thorugh a crash report!

### To Reproduce

Place down multiple large scale nether portals
Attempt to break these portals really quickly (efficiency 255)
Watch as the server runs out of memory.

### Additional Information

![image](https://user-images.githubusercontent.com/30563757/199204056-5bd69b20-903e-47d4-bca5-5afec5327892.png)

https://www.youtube.com/watch?v=vrqLVAoWQJY

(Sent spark and crash report via Discord)

**Comment by Skizzles** [comment]
https://spark.lucko.me/ShzNlRAb7h

**Comment by OmerBenGera** [comment]
Do you have a value set to portal blocks (the actual purple portal, not obsidian)?

**Comment by Skizzles** [comment]
> Do you have a value set to portal blocks (the actual purple portal, not obsidian)?

NETHER_PORTAL: 1

If this is the portal block inside the portal then I swear ahah

**Comment by OmerBenGera** [comment]
> > Do you have a value set to portal blocks (the actual purple portal, not obsidian)?
> 
> NETHER_PORTAL: 1
> 
> If this is the portal block inside the portal then I swear ahah

It was. The issue was caused due to a lot of blocks break all at once, causing many block saving which caused the server to eventually crash.
This should be fixed with latest dev build, as the plugin will not try to save these block counts (they will be saved later).
I ran a spark profiler and it's much better now:
<https://spark.lucko.me/LMdpVWu7oJ>

Let me know if it's better for you as well.

**Comment by Skizzles** [comment]
Works good
