### ISSUE TITLE
IslandUpgradeEvent runs twice

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1490]
### Minecraft's Version

paper 1.12.2

### Plugin's Version

2022.9-b921

### Describe the bug

Why does IslandUpgradeEvent run twice?
![image](https://user-images.githubusercontent.com/41546701/205408142-f7ccdfe8-33ed-4c50-8ab9-56923f4fbad6.png)

### To Reproduce

```
public class UpgradeEvent implements Listener {
    @EventHandler
    public void onUpgradeEvent(IslandUpgradeEvent e) {
        Bukkit.broadcastMessage("Upgrade: "+e.getUpgradeName());
        Bukkit.broadcastMessage("Upgrade Level: "+e.getUpgradeLevel().getLevel());
        Bukkit.broadcastMessage("Upgrade Cost: "+e.getCost());
        Bukkit.broadcastMessage("-----------------");
    }
}
```

### Additional Information

I want to cancel the event, but because it runs twice, I ran into some issues.

**Comment by Superalex0102** [comment]
I managed to fix it by setting `e.getCost().doubleValue() != 0`

**Comment by OmerBenGera** [comment]
The event is called twice because one time is for /is rankup, and the other time to when the upgrade itself executes /is admin setupgrade.
The indicative to a cost of 0 is good enough, however in newer versions I added a cause parameter to the event, so you can filter on this.
I also fixed the first event showing incorrect upgrade level - the event supposed to show you the upgrade level the island is ranking up into, and not the current one :)
