### ISSUE TITLE
player without permission can create island without permission

### ISSUE THREAD

**Issue by luiiszinhoo** [BG-Software-LLC/SuperiorSkyblock2#1492]
### Minecraft's Version

Current: git-Purpur-1857 (MC: 1.19.2)*
Previous: git-Purpur-1842 (MC: 1.19.2)
* You are running the latest version

### Plugin's Version

Version 2022.9

### Describe the bug

the player manages to create the vip island even without having the permission to create, when he adds the permission part in the creation file he gives error.

### To Reproduce

Follow my .yml in pastebin

### Additional Information

https://pastebin.com/D8SaDJbv

Images:

Menu for default player:
https://i.imgur.com/tjbAQG9.png

Console with /is admin reload:
https://i.imgur.com/ajT17Pe.png

Player default execute /is:
https://i.imgur.com/7iiXRth.png

Player with permission execute command:
https://i.imgur.com/wGbJFQY.png 

All islands appear released even without the rank

**Comment by OmerBenGera** [comment]
In older versions of the plugin there was a bug that it didn't show correctly what item cannot be parsed, which is fixed in latest builds already.
The issue occurred because of a mistake in your menu; you configured the `^`'s no access item with the type `PLAINS` instead of `PLAYER_SKULL` - fix it and it will work again :)
