### ISSUE TITLE
Respawing in your island after falling into the void does not cancel momentum and kills you again

### ISSUE THREAD

**Issue by EditChris** [BG-Software-LLC/SuperiorSkyblock2#1607]
### Minecraft's Version

Paper Spigot for 1.19.3, Build 404

### Plugin's Version

2022.9-b975, dev build

### Describe the bug

Basically what the title says. It looks like it's related to the "player-respawn" setting on the config file. I have that by default right now, and after doing some testing with it for a bit, the only settings where the player doesn't die are the VANILLA and BED_TELEPORT ones.

### To Reproduce

1. Go to your island.
2. Fall into the void and die.
3. When you respawn in your island, you will die again. There's a chance for it to not work sometimes, so keep trying, eventually you will die twice for sure.

**Comment by OmerBenGera** [comment]
Hey, sorry for the long waiting time
I tried to jump to void and respawn over 20 times, and haven't died again once (or even took any extra damage)
Please upload your config file to pastebin and send a link to it here

**Comment by EditChris** [comment]
Here it is: https://pastebin.com/NbnvZHEV

**Comment by OmerBenGera** [comment]
Can't replicate the issue even using your config file
Are you able to replicate it yourself on a server with only SuperiorSkyblock installed?
Btw, from what I know, after you die, the server resets your velocity, so in general it shouldn't happen, which is why I don't understand why would it occur in first place, unless another plugin somehow breaks it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
