### ISSUE TITLE
"/Is deposit all" not working properly

### ISSUE THREAD

**Issue by CreeperJockeyJr** [BG-Software-LLC/SuperiorSkyblock2#1624]
### Minecraft's Version

purpur-1.19.2-1856.jar

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

/is deposit all is giving an error to the player, happens at random time. Console shows no error.

### To Reproduce

https://youtu.be/QEGPQisfN5U

**Comment by OmerBenGera** [comment]
What economy plugin are you using?
These errors are mostly related to your economy plugin.

**Comment by airoons** [comment]
Hey @OmerBenGera,

I can add to this more details as I've encountered it myself. So this line https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/Hook_Vault/src/main/java/com/bgsoftware/superiorskyblock/external/economy/EconomyProvider_Vault.java#L45 rounds the transaction amount to #.### (3 decimals after comma).

The issue happens when amount before rounding is smaller than after rounding. For example, `100.9279999` gets rounded to `100.928` and that causes issues...

I resolved this myself by dropping decimals all together (in a SSB2 fork of mine), but you could possibly think of a better solution for this. I hope this will help you!

**Comment by CreeperJockeyJr** [comment]
We use CMI

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
