### ISSUE TITLE
Island Level Math

### ISSUE THREAD

**Issue by ItchyDitchy** [BG-Software-LLC/SuperiorSkyblock2#1668]
### Minecraft's Version

1.19.3
git-Purpur-1933

### Plugin's Version

SuperiorSkyblock2 version 2023.1-b990

### Describe the bug

Math does not... process properly?

### To Reproduce

Change island-level-formula in config, reload the plugin, check island level.

### Additional Information

![image](https://user-images.githubusercontent.com/51221502/229788742-826f8034-b932-42ee-af1d-5b8e9162ed50.png)

**Comment by OmerBenGera** [comment]
Island level is not calculated like this.
It is calculated per block, therefore it takes each block and calculates its level. Because you have rounded-island-level set to true, it will also round all the levels, resulting different levels as you might have expected.
If you use `/is value` on a block, you'll see the level is correct for that specific block (and any other block individually)
