### ISSUE TITLE
Visitors can take books out of lecterns

### ISSUE THREAD

**Issue by OGreenC** [BG-Software-LLC/SuperiorSkyblock2#1670]
### Minecraft's Version

Paper-411 (1.17.1)

### Plugin's Version

2022.9-b977

### Describe the bug

Visitors are able to open a lectern, and read a book (which in itself is fine, and I think it would be a shame to disable this all together by adding the Lectern in the interactables.yml), but they can also take the book, by clicking on the "Take Book" button in the book GUI.

Am I missing a setting in a config file? :-)

### To Reproduce

Visit another players island, and open a lectern with a book. You will be able to take it.

### Additional Information

For your convenience, I found this event, which I believe, should be listened to / cancelled, if the player is not a member of / cooped on the island.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerTakeLecternBookEvent.html

One could even consider to make this a island permission - Though it might be overkill, and would fit nicely in the chest-access permission IMO.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, I added a new permission "PICKUP_LECTERN_BOOK" which should be available on 1.16+
If you can't see it on your permissions menu, reset it or copy the section of that permission manually.
I also recommend adding the permission manually to the config file under the default role (under coop probably?)
