### ISSUE TITLE
Circular plugin loading

### ISSUE THREAD

**Issue by shovelbug** [BG-Software-LLC/SuperiorSkyblock2#1839]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.2

### Describe the bug

when i launch my server after adding superiorskyblock server fails to launch

### To Reproduce

install these plugins
Citizens -> CMI -> DiscordSRV -> Multiverse-Core -> SuperiorSkyblock2 -> Oraxen -> ModelEngine -> Citizens

### Additional Information

https://pastebin.com/cSR1YxYY

**Comment by OmerBenGera** [comment]
You can either remove one of the plugins in this circle to break it, or disable Paper's new loading plugins system.
This is not a bug of SSB.

**Comment by shovelbug** [comment]
it is a bug of SSB i have seen numerous bug reports of this on this plugins bug report history and it occurs if any single one of these plugins is there with SSB, SSB and just CMI, SSB and just citizens, SSB and just Oraxen, further more your solution to disable papers new loading plugins system isnt even new anymore you have been saying this for a while now and as you pointed out in a previous bug report, paper suggested doing this too if a bug report to you didnt work, but the thing you neglect to mention when you tell people that is the other thing Paper devs said about disabling the new plugin loading system, is that it can cause other bugs and issues, the fact that this is an ongoing issue and you have had several bug reports the issue ONLY occurs when SSB is used and you refuse to do anything about it makes this a terrible plugin

**Comment by OmerBenGera** [comment]
> it is a bug of SSB i have seen numerous bug reports of this on this plugins bug report history and it occurs if any single one of these plugins is there with SSB, SSB and just CMI, SSB and just citizens, SSB and just Oraxen, further more your solution to disable papers new loading plugins system isnt even new anymore you have been saying this for a while now and as you pointed out in a previous bug report, paper suggested doing this too if a bug report to you didnt work, but the thing you neglect to mention when you tell people that is the other thing Paper devs said about disabling the new plugin loading system, is that it can cause other bugs and issues, the fact that this is an ongoing issue and you have had several bug reports the issue ONLY occurs when SSB is used and you refuse to do anything about it makes this a terrible plugin

The issue is that SSB has support to many plugins, and some of them might have support to other plugins, that load before SSB.
This not something that can be avoided without removing support for one of the plugins, and this is obviously not a solution.
When Paper designed their new system for loading plugins, they forgot the fact that plugins depend on each other and many times there are "circular dependencies", and they refuse to get it fixed.
You issue in your case is that SuperiorSkyblock must be loaded before MultiverseCore (Cannot be removed, SSB must handle its own worlds), however it also has Oraxen as soft-depend. Oraxen then needs ModelEngine, which needs Citizens - however, Citizens has some relation with CMI, that has some relation to DiscordSrv, which for no reason needs to be loaded before MultiverseCore - and that's the conflict.
This is not something SSB can somehow avoid; Therefore, the only solution is to disable Paper's system, or get rid one of the plugins to break this chain.

If you don't like this solution, you'll have to either find a solution yourself or get another plugin.
