### ISSUE TITLE
island worth/value going into negative when it is set to false in config 

### ISSUE THREAD

**Issue by Swoochy** [BG-Software-LLC/SuperiorSkyblock2#1871]
### Minecraft's Version

1.19.4 Paper

### Plugin's Version

lastest as of this

### Describe the bug

island can into in the minus even when the setting is disabled eg: false

### To Reproduce

issue

**Comment by OmerBenGera** [comment]
It works fine for me.
I set both `negative-worth` and `negative-level` and `/is show` shows that I have 0 instead of negative values.
Btw, this feature doesn't actually making you not have negative level/worth, it is only shows as you have 0 level/worth, while in reality you still have negative level/worth. If you want to completely remove the ability to have negative level/worth, make sure you disable the `offset` feature in the creation menu from the schematics. For existing islands, you'll have to run `/is admin syncbonus` so their level/worth adjustments will be synced again.

**Comment by Swoochy** [comment]
# Can the worth value of the island be negative?
negative-worth: false

# Can the level of the island be negative?
negative-level: false

 # Should the schematics in this world will not be counted towards worth and level values?
 schematic-offset: true


this is the settings i have. still possible to do so

**Comment by Swoochy** [comment]
it is also still counting the offset. so when i create an island it is showing the worth

**Comment by Swoochy** [comment]
so it shows 0 in /is show but the placeholder for island worth is shows the offset of things placed

**Comment by OmerBenGera** [comment]
> so it shows 0 in /is show but the placeholder for island worth is shows the offset of things placed

What placeholder are you using?

**Comment by Swoochy** [comment]
tried 

superior_island_raw_worth_format
superior_island_worth_format

both return the same

**Comment by Swoochy** [comment]
Sorry this now works. thank you.
