### ISSUE TITLE
FarmingMission barely registering growing pumpkins/melons or anything

### ISSUE THREAD

**Issue by Pinchuini481** [BG-Software-LLC/SuperiorSkyblock2#2215]
### Minecraft's Version

1.20.4

### Plugin's Version

2024.2

### Describe the bug

the mission only recognises like 1 in 10 pumpkin grows, so let's say i grow 10 pumpkins. it will say i grew one. i planted them myself and i can't seem to find why doesn't recognize it most of the time.

### To Reproduce

just install the plugin and try to do the mission, i think all of them barely work

### Additional Information

![image](https://github.com/user-attachments/assets/626bdc09-9124-492f-a8fa-344fc0e53452)

**Comment by Pinchuini481** [comment]
after testing a lot i have a little more info, if i plant it and stay online, i SSB does notice it and just gives me +1 for pumpkin or whatever. however if i go offline and come back online later. it's like the game completely forgot that i planted the crops. so even if it grows when i'm alone. it doesn't get added to my missions

**Comment by Pinchuini481** [comment]
latest dev build fixed it, sorry

**Comment by Srcsm** [comment]
I just want to add that I was able to replicate this, even though they mention it resolved for them.

Here are my count _before_ a restart. I've let some crops grow before restarting, but I haven't harvested them yet:
![image](https://github.com/user-attachments/assets/40d18e84-fe4b-4b4c-a1ee-315918819bda)

Here's after restarting, and harvesting the crops I had let grow, as well harvesting multiple in-game days worth of regrowth:
![image](https://github.com/user-attachments/assets/39d886fb-7752-4461-86fb-b4925fe4878c)
None if it counted towards my counts. The melons being 1 off is because I had accidentally broke the main plant of a melon, so replanted it since the restart and used bone meal on it and it grew a melon right away.

After removing all the main pumpkin and melon plants, replanting them all, letting them grow and then harvesting them, my counts increase:
![image](https://github.com/user-attachments/assets/ae29a04b-9517-43de-80f6-c67af3056018)

Paper 1.20.4-497 and SuperiorSkyblock2 v2024.2-b311

**Comment by AlmostPanda** [comment]
> I just want to add that I was able to replicate this, even though they mention it resolved for them.
> 
> Here are my count _before_ a restart. I've let some crops grow before restarting, but I haven't harvested them yet: ![image](https://private-user-images.githubusercontent.com/11580870/362106003-40d18e84-fe4b-4b4c-a1ee-315918819bda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODAzNTUsIm5iZiI6MTcyNDg4MDA1NSwicGF0aCI6Ii8xMTU4MDg3MC8zNjIxMDYwMDMtNDBkMThlODQtZmU0Yi00YjRjLWExZWUtMzE1OTE4ODE5YmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIxMjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOTMzMzc2OWRlNjkwMzIzN2I1ZGY4NmFiODFhNGRhNzJhMjNiMmFkODUyODM0Y2E2MmM2NGFmY2E1NmM3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3DaFKbQyat9sOIVUJZFcqeRk6GXKY0Ctge9Pp5a3E4)
> 
> Here's after restarting, and harvesting the crops I had let grow, as well harvesting multiple in-game days worth of regrowth: ![image](https://private-user-images.githubusercontent.com/11580870/362106285-39d886fb-7752-4461-86fb-b4925fe4878c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODAzNTUsIm5iZiI6MTcyNDg4MDA1NSwicGF0aCI6Ii8xMTU4MDg3MC8zNjIxMDYyODUtMzlkODg2ZmItNzc1Mi00NDYxLTg2ZmItYjQ5MjVmZTQ4NzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIxMjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZTFkMTBhZTAwNTExZWRkNGZiNGY2MGMxOWUzMmY4MDEzODExNjRhMWM2M2FjNzY4NzM3ODhiODRmNzM5YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfwKZS2affn5rprOczkEvKq57e5F990DQOSWzZUlpOw) None if it counted towards my counts. The melons being 1 off is because I had accidentally broke the main plant of a melon, so replanted it since the restart and used bone meal on it and it grew a melon right away.
> 
> After removing all the main pumpkin and melon plants, replanting them all, letting them grow and then harvesting them, my counts increase: ![image](https://private-user-images.githubusercontent.com/11580870/362106755-ae29a04b-9517-43de-80f6-c67af3056018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODAzNTUsIm5iZiI6MTcyNDg4MDA1NSwicGF0aCI6Ii8xMTU4MDg3MC8zNjIxMDY3NTUtYWUyOWEwNGItOTUxNy00M2RlLTgwZjYtYzY3YWYzMDU2MDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIxMjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYmEyY2ZjZTM4NTM1ZmFkNjg2OThmYzM3ODE3MGUxY2UwNjYwM2Y5ZDZhNDI2NzRkNjM3YmQ1NjYwNTVlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TIixzoTKioblLH5rY6B8D2jv0h_3M0h90lTfFit3pGo)
> 
> Paper 1.20.4-497 and SuperiorSkyblock2 v2024.2-b311

same thing happens for me, but also with cactus/sugar cane if I plant it and restart server then when it grow up it doesnt count but if I replant it, it counts
it also works on crops like wheat, beetroots and other, just plant it and restart server, when it grows up it doesnt count

using Paper 1.21-130 (last build) and SuperiorSkyblock2 v2024.2-b311

BUT
after deleting whole datastore folder, and starting server, it seems to work again without any issue, so maybe some problem with saving data to database? dont know

**Comment by AlmostPanda** [comment]
@OmerBenGera 
can you take a look at it when you will be free, please

**Comment by OmerBenGera** [comment]
> @OmerBenGera can you take a look at it when you will be free, please

Open a new issue regarding this.
You said it works for you on clean setup, so it's probably something related to your specific setup.

**Comment by AlmostPanda** [comment]
> Open a new issue regarding this. You said it works for you on clean setup, so it's probably something related to your specific setup.

yeah it works on clean setup, then I add the plugin on live server and it didnt work so I made a copy of live server database and moved it on my local test server and it still didnt work, then I left it behind for around 2 weeks, meanwhile I made a 1.21 update on my another test server....

I think I forgot to replant crops when you made the fix for FarmingMission and thats why it didnt work, because now I jumped on our live 1.20.4 server where it didnt count, replanted made a restart and not it counts
so Im just dumb and its probably really fixed on my side.

sorry about that
