### ISSUE TITLE
Schematic cut off when outside border

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#230]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
dev-126

**Describe the bug**
When a schematic is outside the border, on island creation it gets cut off.

**Comment by Skizzles** [comment]
@OmerBenGera You had fixed this in the past from happening and it seems to have started again since I updated the plugin to 126 from 112.

**Comment by Skizzles** [comment]
To add onto this issue, the island generation seems to be changed a lot lately.... How my island schematic is supposed to be:
https://screenshots.skizzles.me/wAnA3/pahATIQo01.png

How SSB generates it:
https://screenshots.skizzles.me/wAnA3/rukUHUyu11.png
(Slabs get messed up, double grass is not proper)

**Comment by OmerBenGera** [comment]
@Skizzles Show me your config, it's something to do with that.

**Comment by Skizzles** [comment]
@OmerBenGera 

https://pastebin.com/SNzyHR6z

**Comment by OmerBenGera** [comment]
You have optimize worlds enabled.
"  # Should the plugin optimize the island worlds?
  # When enabled, only chunks of islands will be saved from the island worlds."
  
  Therefore, due to the schematic being outside of the border, and the chunks outside of the border not being saved... it causes the schematic to be cut. I recommend to not have that option enabled.
