### ISSUE TITLE
Bug with graalvm

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#245]
**Minecraft's Version**
Yatopia-108

**Plugin's Version**: -
superiorskyblock-133

**Describe the bug**
Graalvm causes issues everytime I break a block
https://pastebin.com/BhLFXxpf

**To Reproduce**
Use graalvm

**Additional information**
This ONLY happen on graalvm, but on default java-11 it works without error
Used the latest graalvm release (quay.io/rikodev/pterodactyl-graalvm:latest)

**Comment by WarnDangerous** [comment]
I also saw this error when starting the server : 
https://pastebin.com/ZhMF60N1

**Comment by WarnDangerous** [comment]
I also saw this error when turning off the server (on DEFAULT java)
https://pastebin.com/T7Q2CL78

I set all my errors into one tickets, but I can open other tickets if you want

**Comment by OmerBenGera** [comment]
Are you using java15...?

**Comment by WarnDangerous** [comment]
No java 11

**Comment by OmerBenGera** [comment]
Why are you using Graalvm?

**Comment by OmerBenGera** [comment]
Also you said it works fine on default java11, so I am not sure what's the issue

**Comment by WarnDangerous** [comment]
To get more performances

**Comment by WarnDangerous** [comment]
I use graalvm because it offers more performances.

but the 2 other issues were on java 11

**Comment by OmerBenGera** [comment]
Well it seems like Graalvm doesn't support the same methods that the regular java script methods are using, therefore it is not supported. Feel free to make a PR for that.
About the other errors, that's due to the plugin changing final modifiers and your java version sends warning about that, this can be ignored.
I am closing this for now, next time don't mix two different issues in the same report.
