### ISSUE TITLE
error help pls

### ISSUE THREAD

**Issue by russianpeanut** [BG-Software-LLC/SuperiorSkyblock2#332]
**Minecraft's Version**
Paper 1.16.5

**Plugin's Version**: -
1.7.0 

**Describe the bug**
i have this error on startup and i cantr join the server and when i remove the plugin its ok 
https://pastebin.com/zyxtwhvJ

**To Reproduce**
sorry idk what that menas

**Additional information**
i dont have schematics folder in superiorskyblock2 folder

**Comment by OmerBenGera** [comment]
You probably use Java 16 and that's why it happens.
You can get rid of this error and get the plugin to load by installing the following module:
https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine

Simply download the jar located under the releases tab and drag it to your modules folder.
