### ISSUE TITLE
Crash on /is biome

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#344]
**Minecraft's Version**
Airplane 1.16.5

**Plugin's Version**: -
Dev build b177

**Describe the bug**
Server crashed when a player did a /is biome and changed his biome

**Additional information**
Report in console :
https://pastebin.com/kjbF7pPG

Crash_log : 
https://pastebin.com/ttEMFXAe

java version : 
Graalvm 21.1.0 EE java 16
Island size : maximum 250x250

**Comment by OmerBenGera** [comment]
You ran out of memory, I recommend increasing the ram for your server.

**Comment by WarnDangerous** [comment]
I got 20gb of allocated memory,
I also tried with 50gb, same issue.

I didn't get the issue on older plugin version, so it's more an issue on your side
(I also tried without any flags, on openJDK 16, so no graalvm, still the error.)

**Comment by WarnDangerous** [comment]
Tried on Superior 1.7.0, can't reproduce the issue, so it's on your side.

**Comment by OmerBenGera** [comment]
As I told you in the other issue, something blocks creation of threads.
Fix it and everything will work again.
If other people will have this issue as well, I'll see what can be done regarding this, but I doubt it's an issue with the plugin (especially due to the fact that nothing changed regards threads creation)
