### ISSUE TITLE
Island teleport issue

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#448]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b220

### Describe the bug

When the spawnpoint of your island is already 'used' (for example there is a block on it), it will redefine your island warp far away at a random place on your island.

But it can create issue, for example : 
- I use "apiaenvoy" that spawn a temporaly shulker box in the center of your island and remove it once you took the items.
But if a player do "/is" when a shulker is on his "island block teleport", it will change his /is to another random point, and this point will become the new /is tp.

it wouldn't be possible to change that, for exemple trying to teleport to the nearest block of the actual it tp position ?

### To Reproduce

place a block on your /is tp spawnpoint, and do /is again.
Even if you break the block on your old /is tp spawnpoint, your spawnpoint is changed

**Comment by OmerBenGera** [comment]
This is an intended behavior. If the plugin can't find a safe spot in the center of the island, it will start looking for a random safe spot on your island, somewhere. If it finds one, it sets the teleport location to this location and teleports the player, otherwise it sends an error message to the player.
The best approach is to not place the envoy at the center, but in an offset of one block or something.
