### ISSUE TITLE
Making your island home unsafe resulting being teleported outside the island border

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#476]
### Minecraft's Version

1.17.1 Purpur 1331

### Plugin's Version

Dev Build 224

### Describe the bug

If your island warp is unsafe, you will get teleported the the most north-western block inside the island border. However after doing it the second time, you will land on the north-western corner of the most north-western block, if that is the corner of the island you will actually be teleported outside of the border.

### To Reproduce

Step 1: Set a safe island home, and fill up a whole island layer
Step 2: Make the island home unsafe by placing a block in it
Step 3: Use /is go twice, the first time you will land on the corner block, the second and every time after that you land on that same block but on the edge so you are outside the border.

### Additional Information

https://youtu.be/AdhsMs7XzxI
This could maybe just be fixed by always tping the player in the middle of the block instead of the corner?

**Comment by OmerBenGera** [comment]
There are actually two issues:
1) The plugin for no reason teleports you to a random block, instead of teleporting you to the block you have just placed.
The algorithm of finding a new safe place should first check if there's a valid block to be teleported in the center, and only if there isn't start looking for blocks across the island.
2) The bug you mentioned, which should obviously teleport you to the middle of the block - however that doesn't happen.

I will look into both of the bugs.

**Comment by OmerBenGera** [comment]
Both issues are fixed in latest dev build.
I also change the algorithm that looks for safe blocks to find blocks that are more close to the original teleport location
