### ISSUE TITLE
Value Registration issue possible hook issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#481]
### Minecraft's Version

1.8.8

### Plugin's Version

Build #237

### Describe the bug

Sometimes shopguiplus prices for buy and sell does not register the block values in the island worth even though it's setup right and randomly happens as seen in the gif i did the value check on the block and the recalc and it still didn't change anything and this happened in the beginning too i noticed it when i was testing the plugin the first couple of times for stuff involving prices and had it on buy and i was trying to focus on more important things to setup the plugin before i come to conclusions and now i'm nearing the end of setting it up so i check the issue if it happens again and it does.

Also sometimes the island values of blocks that were already there show up as the island value randomly as well.

### To Reproduce

I don't know what to tell you if it's random

### Additional Information

https://gyazo.com/ac0b404634d780f7b74637fca7441fdc

**Comment by OmerBenGera** [comment]
Check in /is counts if they are counted or not.
If they are there, then they are counted towards your island level and worth values.
Also, if the prices are taken from SGP and they are correct in /is values, then there is no issue with the hook and your issue is misleading. Please correct all the information provided with the actual issue, as I don't quite understand the source of the issue.

**Comment by MineagePvP** [comment]
i will as soon as tomorrow since i am not home currently and went to canada

**Comment by MineagePvP** [comment]
i'm gonna make a video later and show you when i wake up i need to take a nap i had a long day

**Comment by MineagePvP** [comment]
Also i just seen issue #485 seems to be having the same issue similar to this and that issue has happened to me as well with the is level
