### ISSUE TITLE
It is not possible to deposit on the island

### ISSUE THREAD

**Issue by YuiDG** [BG-Software-LLC/SuperiorSkyblock2#588]
### Minecraft's Version

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.7.0-DEVb296

### Describe the bug

Well, when I deposit in the island bank, it removes my money, but it doesn't go to the island bank. If I deposit half, the bank withdraws half and doesn't go to the island, and if I deposit everything I practically lose my money, and the problem also occurs when depositing a certain amount. I have also tested various types of "economical" plug-ins to see if this is the problem, or I even changed the version to 1.16.5 - 1.17, I also changed the plug-in version, but the bug remains. The strangest thing is that there are no errors on the console.

I used google translator, good night ☕

### To Reproduce

1. Have money in your account
2. Try to deposit money on your island

### Additional Information

https://imgur.com/DiDH0wM
the video is over 10MB

OwO

**Comment by OmerBenGera** [comment]
What is that error message? Did you change your messages or its default?

**Comment by YuiDG** [comment]
default

**Comment by OmerBenGera** [comment]
The error is due to your economy plugin setting this as an failure message (I don't know why, but that's how they think people will understand what caused the failure to occur).
Try using another economy plugin, as it seems like they set an error/failure message even when the transaction succeeds, making the plugin to cancel the operation even if the transaction was successfully made.

**Comment by YuiDG** [comment]
ok
