### ISSUE TITLE
Island missions in progress reset when server restarts

### ISSUE THREAD

**Issue by JLucassz** [BG-Software-LLC/SuperiorSkyblock2#847]
### Minecraft's Version

Minecraft 1.17.1

### Plugin's Version

SuperiorSkyblock2-1.8.3-b444.jar

### Describe the bug

When a player is doing a quest, for example, he got 32 diamonds and the server restarts. When the server comes back, its progress will be reset to 0 diamonds.

### To Reproduce

Doing a quest but not completing it, just progressing it and then restarting the server.

### Additional Information

I believe that somehow the progress is not being saved in the database. On my server I put superiorskyblock in the server database.

**Comment by Skizzles** [comment]
I am unable to replicate this on the above setup. What server jar are you using? Also are you able to replicate this issue with just SuperiorSkyblock installed? Is it every mission or just one?

**Comment by Trinchezito** [comment]
is happening on my server too. People missions get reset especially the mining ones.

**Comment by Skizzles** [comment]
> is happening on my server too. People missions get reset especially the mining ones.

Please avoid commenting "me too", provide information to help resolve and identify the issue.

**Comment by ripperfame1** [comment]
we have figured out that island missions do not reset. For farming missions you have to hold "500" of said items "Wheat,pumpkin,potatoes" in inventory once u take out of inventory the count goes to 0
once the missions is claimed it will take "500" of those items and you'll be able to complete the missions

**Comment by ripperfame1** [comment]
@JLucassz

**Comment by Silarious** [comment]
### Minecraft's Version
Minecraft 1.17.1

### Plugin's Version
1.8.4-b501

### Bug
Similar to the aforementioned bug but specifically when adding new missions, all completed missions status are reset while partially completed are not.

For example the result is if missions Miner 1 through 3 are completed but 4 is partially completed, after reproduction steps, mission 1 through 3 are 0% while miner 4 has the same progress.

### Reproduction

1. Complete missions or force complete with `/is admin mission` command.
2. Create a new mission, seems to be any mission in any category.
3. Restart server
4. View mission UI completed missions will be reset and partially completed missions and their progress remain.

**Comment by DuckyDou** [comment]
Same issue 1.18.1

**Comment by OmerBenGera** [comment]
Check if the progress is saved to the data filw when you close the server. After you check it, start it again and send the results.

**Comment by n54b** [comment]
nothing save in _data.yml (when missions is complete)

**Comment by Trinchezito** [comment]
:C no fixes as of Build #507
Players keep losing mission progress when server is restarted. No errors in the console for me.

**Comment by OmerBenGera** [comment]
None of you have yet answered my question above.

**Comment by n54b** [comment]
Check if the progress is saved to the data filw when you close the server. After you check it, start it again and send the results 
=> THIS ???
I answer !! nothing save in _data.yml (when missions is complete)

**Comment by OmerBenGera** [comment]
> Check if the progress is saved to the data filw when you close the server. After you check it, start it again and send the results => THIS ??? I answer !! nothing save in _data.yml (when missions is complete)

Again, don't check it when a mission completes (when it completes, there will be no data for the missions, as there's nothing to track for the mission - it's already completed).
Check when you have data tracked, if it doesn't get saved after you close the server.
Also, missions' data is saved every 5 minutes besides being saved when server stops.

**Comment by n54b** [comment]
for me its only "ItemsMissions" so no progress only complete ...

**Comment by OmerBenGera** [comment]
> for me its only "ItemsMissions" so no progress only complete ...

ItemsMissions do not track any data.
They check if you have enough items in your inventory once you try to complete it.

**Comment by n54b** [comment]
nothing in _data.yml i wait 30 min with one mission complete, one mission can completed but nothing inside ...

**Comment by OmerBenGera** [comment]
> nothing in _data.yml i wait 30 min with one mission complete, one mission can completed but nothing inside ...

I will add debug messages so we can better understand what is going on.

**Comment by evildeedz** [comment]
> > Check if the progress is saved to the data filw when you close the server. After you check it, start it again and send the results => THIS ??? I answer !! nothing save in _data.yml (when missions is complete)
> 
> Again, don't check it when a mission completes (when it completes, there will be no data for the missions, as there's nothing to track for the mission - it's already completed). Check when you have data tracked, if it doesn't get saved after you close the server. Also, missions' data is saved every 5 minutes besides being saved when server stops.

Here is what I found after diving deep into investigation for the missions bug. Downgrade seems to be the only thing that worked. However here my notable findings that will help you tackle this bug

1) When I downgraded from 1.8.4, the _data.yml didnt have any data of the missions as I deleted and regenerated the file (restarted server twice ofc). All mission data was stored in the database. So when I restarted the server with 1.8.3 the missions worked agian.. even when there was nothing in _data.yml.. which makes me think that the plugin retrieves data from the database itself (the player_missions table).
2) No data was saved in 1.8.4 on mission completes in _data.yml, after 20 minutes of wait.. or on server restarts, although I did /is  admin mission command to complete mission. This however, did store my mission progress in the database, but nothing ever showed  up in the _data.yml file. However when I restarted server, missions reset... BUT the data that my mission was completed was still in the player_missions table. I tried this with a fresh database too, and same thing.
3) This leads me to conclude that for some reason, when server restarts, doesn't matter an upgraded database from a previous version, or a new database, the problem is 1.8.4 is unable to read the island  missions. I tried this with _data.yml having  full information of players who did misisons in 1.8.3 and then upgrading to 1.8.4, it still didnt work. This means that 1.8.4 is unable to retrieve missions data from the database.

What can you do?
Downgrade. This wouldn't come without issues tho. One major problem that you will face undoubtedly.. is that island upgrades would be messed up as the island_upgrades would use a primary  key.. if it does, just let me know on discord AL. EviL DeEdZ#1809 and i will solve it for u.

**Comment by xunder-matth** [comment]
I can confirm that player's mission progress is successfully saved in `_data.yml` but completed missions are not loaded from database after server restart.

**Comment by OmerBenGera** [comment]
There was an issue with completed missions not being loaded from database correctly.
This issue is fixed in latest dev build. Let me know if progress is fixed as well

@xunder-matth @DuckyDou @evildeedz

**Comment by rentexfamily** [comment]
> There was an issue with completed missions not being loaded from database correctly. This issue is fixed in latest dev build. Let me know if progress is fixed as well
> 
> @xunder-matth @DuckyDou @evildeedz

It's fixed but there is another issue with missions. I'll open new issue.

**Comment by OmerBenGera** [comment]
Any news regarding this?
