### ISSUE TITLE
/is reset in combination with slimefun causes massive tps spikes

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#850]
### Minecraft's Version

1.17.1

### Plugin's Version

dev build 468

### Describe the bug

Whenever a player issues th /is reset command, the tps will go down for quite a bit.
Timings showthat this is due to the combination of ssb with slimefun.
https://i.imgur.com/Q0ZMh7P.png

### To Reproduce

Have both slimefun and SUperiorSkyblock2 installed
Create an island, and /is reset that island

### Additional Information

https://pastebin.com/kYyu871z

**Comment by OmerBenGera** [comment]
This is because SSB deletes data of Slimefun when chunks resets.
Open an issue on their github, tag me there as well, and ask if there is a better solution for doing that. Also include the class that does the logic (https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/003ed9c0e4264b925c98898ebb619f13d4beb46a/Hook_Slimefun/src/main/java/com/bgsoftware/superiorskyblock/hooks/support/SlimefunHook.java#L87)
If you prefer that I will do it, then I dont mind doing so, however I will only be able to do that on the weekend.

**Comment by OmerBenGera** [comment]
I will let you know once its patched :)

**Comment by OmerBenGera** [comment]
I am closing this. For updates, check out the slimefun issue

**Comment by Skizzles** [comment]
@OmerBenGera 

I feel Slimefun won't get to fixing this on their end any time soon. Surely there is a way to process these changes over time or some more optimized way?

**Comment by OmerBenGera** [comment]
> @OmerBenGera
> 
> I feel Slimefun won't get to fixing this on their end any time soon. Surely there is a way to process these changes over time or some more optimized way?

Not really. Ask them again to implement it.

**Comment by OmerBenGera** [comment]
@Skizzles Check out latest dev build, let me know how is it doing.

**Comment by OmerBenGera** [comment]
> > @Skizzles Check out latest dev build, let me know how is it doing.
> 
> Seems to not have a lag spike, but this does not fully wipe the Sf block storage as it should: https://screenshots.skizzles.me/wAnA3/hEQOmibu47.png

Should be reported to Slimefun.
I use the method that they added - if it doesn't clear all the data, then it is an issue on their side.
