### ISSUE TITLE
Permissions dont work for schematics

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#902]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b498

### Describe the bug

Schematics with required permission anyway can be created, even if player dont have required permission

### To Reproduce

Set any required permission for schematic
Try to create island

**Comment by OmerBenGera** [comment]
Upload your menu file to pastebin and send it here please.

**Comment by exzolink** [comment]
> Upload your menu file to pastebin and send it here please.

https://pastebin.com/McUT6uFq

**Comment by exzolink** [comment]
In b390 works as should

**Comment by OmerBenGera** [comment]
You are correct, the `required-permission` field was used before and got removed, it's not longer used.
Now, instead of using this field, you have the ability to use a more generic way that works for every item in the menu.
Read more about it here: https://wiki.bg-software.com/superiorskyblock/menus#permissions-section
