### ISSUE TITLE
Bypass pvp/damage island setting

### ISSUE THREAD

**Issue by iMaarten** [BG-Software-LLC/SuperiorSkyblock2#91]
Players are able to kill other players with Tridents and fireworks and crossbows

**Comment by OmerBenGera** [comment]
I can't replicate the issue, everything works fine for me

**Comment by iMaarten** [comment]
https://www.youtube.com/watch?v=jiFV05u2YZ0

**Comment by OmerBenGera** [comment]
I can't replicate the issue, as I said earlier.
I am using a burst, blue firework for that

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by iMaarten** [comment]
https://youtube.com/shorts/_c2lClY-T0o

Here is another video hope that helps..

**Comment by OmerBenGera** [comment]
I already said that the issue cannot be replicatable, and it might be because of your spigot jar.
Make sure you use latest one available for your version. Also, I even said how I tried to replicate it and haven't received a response from you, so you'll have to let me know which firework exactly was used so I can try and replicate the issue.
Besides that, make sure you use latest dev build of SSB from the website.

**Comment by OmerBenGera** [comment]
Any news regarding this?
