### ISSUE TITLE
FarmingMissions

### ISSUE THREAD

**Issue by KibbaCrafteR** [BG-Software-LLC/SuperiorSkyblock2#920]
### Minecraft's Version

1.8.8

### Plugin's Version

1.8.4

### Describe the bug

How I could use like the FarmingMissions when i break they aren't working how to use them

### To Reproduce

How I could use like the FarmingMissions when i break they aren't working how to use them, they doesn't show any progress % or break counts

**Comment by Trinchezito** [comment]
Unfortunately, you have to have the farming items in your inventory, otherwise this skyblock plugin doesn't read them.

**Comment by Skizzles** [comment]
Which farming item specifically? All mine are working correctly.

**Comment by KibbaCrafteR** [comment]
> Which farming item specifically? All mine are working correctly.

Could I have your configs please

**Comment by Skizzles** [comment]
> > Which farming item specifically? All mine are working correctly.
> 
> Could I have your configs please

No, but you could provide me yours so I could see what the issue is.

**Comment by OmerBenGera** [comment]
I see that there's a misunderstanding of how the mission works.
FarmingMissions is not checking when you break blocks or whether you have items in your items - for that you have BlocksMissions and ItemsMissions. FarmingMissions tracks data when a crop that you planted growth to its final stage.
You must be the player that plants the crop, otherwise it won't track progress for you.

**Comment by OmerBenGera** [comment]
Any news regarding this?
